# Generated by Django 4.0.3 on 2022-04-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Name', models.CharField(max_length=25)),
                ('Emp_ID', models.IntegerField()),
                ('Emp_Designation', models.CharField(max_length=40)),
                ('Emp_Date_Of_Joining', models.IntegerField()),
                ('Emp_Department', models.CharField(max_length=20)),
                ('Emp_Salary_Package', models.IntegerField()),
                ('Emp_Experince', models.IntegerField()),
            ],
        ),
    ]
