# Generated by Django 4.0.3 on 2022-04-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emp_Data',
            new_name='Empdata',
        ),
    ]
