# Generated by Django 4.0.3 on 2022-04-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_emp_data_empdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='Emp_Date_Of_Joining',
            field=models.DateField(),
        ),
    ]
