# Generated by Django 4.0.3 on 2022-04-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_calender_rename_latest_news_news_occation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Occation',
            new_name='Occations',
        ),
    ]
