# Generated by Django 4.0.3 on 2022-05-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_occation_news_occations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='date',
            new_name='Date',
        ),
    ]
